name: Auto-update from PyPI

on:
  schedule:
    # Check for updates daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-formula:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
          
      - name: Check for new version
        id: check_version
        run: |
          # Get current version from formula
          CURRENT_VERSION=$(grep -E '^\s*url.*rxiv_maker-' Formula/rxiv-maker.rb | sed 's/.*rxiv_maker-\([0-9.]*\)\.tar\.gz.*/\1/')
          echo "Current version: $CURRENT_VERSION"
          
          # Get latest version from PyPI
          LATEST_VERSION=$(curl -s "https://pypi.org/pypi/rxiv-maker/json" | python3 -c "import sys, json; print(json.load(sys.stdin)['info']['version'])")
          echo "Latest version: $LATEST_VERSION"
          
          # Compare versions
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "New version available: $LATEST_VERSION"
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "new_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "No update needed"
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Update formula
        if: steps.check_version.outputs.update_needed == 'true'
        run: |
          NEW_VERSION="${{ steps.check_version.outputs.new_version }}"
          
          # Get SHA256 hash from PyPI
          SHA256=$(curl -s "https://pypi.org/pypi/rxiv-maker/json" | \
                  python3 -c "
          import sys, json
          data = json.load(sys.stdin)
          for file_info in data['releases']['$NEW_VERSION']:
              if file_info['packagetype'] == 'sdist':
                  print(file_info['digests']['sha256'])
                  break
          ")
          
          echo "New SHA256: $SHA256"
          
          # Update formula using sed
          sed -i.bak "s|rxiv_maker-[0-9.]*\.tar\.gz|rxiv_maker-$NEW_VERSION.tar.gz|g" Formula/rxiv-maker.rb
          sed -i.bak "s|sha256 \"[a-f0-9]*\"|sha256 \"$SHA256\"|g" Formula/rxiv-maker.rb
          
          # Remove backup file
          rm Formula/rxiv-maker.rb.bak
          
      - name: Update Python dependencies
        if: steps.check_version.outputs.update_needed == 'true'
        run: |
          NEW_VERSION="${{ steps.check_version.outputs.new_version }}"
          
          # Get dependency information from PyPI
          echo "Fetching dependency information for version $NEW_VERSION..."
          
          # This would ideally update all resource SHA256s, but for now we'll
          # just update the main package and let manual review handle deps
          echo "Note: Python dependency versions should be manually reviewed"
          
      - name: Test updated formula
        if: steps.check_version.outputs.update_needed == 'true'
        run: |
          # Install formula locally first
          brew install --formula ./Formula/rxiv-maker.rb
          
          # Validate formula syntax
          brew audit --strict rxiv-maker
          
          # Test formula parsing
          brew info rxiv-maker
          
          # Verify download URL
          NEW_VERSION="${{ steps.check_version.outputs.new_version }}"
          URL="https://files.pythonhosted.org/packages/source/r/rxiv-maker/rxiv_maker-$NEW_VERSION.tar.gz"
          curl -I -f "$URL"
          echo "Download URL is valid"
          
      - name: Create Pull Request
        if: steps.check_version.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update rxiv-maker to version ${{ steps.check_version.outputs.new_version }}"
          title: "Auto-update: rxiv-maker ${{ steps.check_version.outputs.current_version }} → ${{ steps.check_version.outputs.new_version }}"
          body: |
            ## Auto-update from PyPI
            
            **Previous version:** `${{ steps.check_version.outputs.current_version }}`
            **New version:** `${{ steps.check_version.outputs.new_version }}`
            
            ### Changes
            - Updated version number in formula
            - Updated download URL
            - Updated main package SHA256 checksum
            
            ### Manual Review Required
            - [ ] Review Python dependency versions
            - [ ] Update resource SHA256s if needed
            - [ ] Test installation on macOS and Linux
            - [ ] Verify CLI functionality
            
            ### Verification
            - [x] Formula syntax validated
            - [x] Download URL verified
            - [ ] Installation testing (pending review)
            
            **PyPI Release:** https://pypi.org/project/rxiv-maker/${{ steps.check_version.outputs.new_version }}/
            **Release Notes:** https://github.com/henriqueslab/rxiv-maker/releases/tag/v${{ steps.check_version.outputs.new_version }}
            
            This PR was automatically created by the update workflow.
            Manual review is recommended before merging.
          branch: auto-update-${{ steps.check_version.outputs.new_version }}
          delete-branch: true
          labels: |
            auto-update
            dependencies
            review-required